adding create_dataentity
getmetal/metal-python pull request #38
Opened 2023-09-15 10:48 UTC by pariosur

Adding: 
- Create Data Entity method

2023-09-15 14:51 UTC, softboyjimbo commented on src/metal_sdk/metal.py
> +        if file_type not in supported_types:
we accept other file types now - docx, xlsx, etc. the api **should** restrict this as well so may be easier to let the server do its thing. what do you think? cc @Czechh

2023-09-16 09:33 UTC, pariosur commented on src/metal_sdk/metal.py
> +        if file_type not in supported_types:
awesome - will modify

2023-09-16 18:09 UTC, Czechh commented on src/metal_sdk/metal.py
> +        if file_type not in supported_types:
yeahh good call!

2023-09-18 13:17 UTC, pariosur commented
@Czechh @softboyjimbo added tests for the new functions

2023-09-18 13:27 UTC, Czechh approved these changes

2023-09-18 18:57 UTC, pariosur commented
@Czechh @softboyjimbo  added the create_index method too, please lmk if it looks ok

2023-09-18 20:05 UTC, Czechh reviewed
Just one comment

2023-09-18 20:05 UTC, Czechh commented on src/metal_sdk/metal.py
> +    def __create_dataentity_resource(self, datasource, filename, file_size):
Nit Here I think `datasource` is correct to be one word, but `dataentity` should be `data_entity`

2023-09-18 20:05 UTC, Czechh commented on src/metal_sdk/metal.py
> +    def create_dataentity(self, datasource, file_path):
same here `create_data_entity`

2023-09-18 20:05 UTC, Czechh commented on src/metal_sdk/metal.py
> +    def get_dataentity(self, id: str):
`get_data_entity`

2023-09-18 20:05 UTC, Czechh commented on src/metal_sdk/metal.py
> +    def delete_dataentity(self, id: str):
`delete_data_entity`

2023-09-18 20:42 UTC, Czechh requested changes
Some changes needed

2023-09-19 09:19 UTC, pariosur commented on src/metal_sdk/metal.py
> +    def __create_dataentity_resource(self, datasource, filename, file_size):
perfect! fixed

2023-09-19 09:20 UTC, pariosur commented
@Czechh fixed! also done for data_entities

2023-09-19 15:39 UTC, merged